repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff-format

  - repo: local
    hooks:
      - id: check-non-latin
        name: Check for non-Latin characters
        entry: uv run python .pre-commit-hooks/check-non-latin.py
        language: system
        files: \.(py|json|yml|yaml|toml|md|txt|js|ts|tsx|jsx)$
