name: Bump Version from Tag

on:
  push:
    tags: ['v*']

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        # Checkout main branch instead of tag
        ref: main

    - name: Verify this is a tag event
      run: |
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"

        # Check if this is actually a tag push event
        if [[ "$GITHUB_EVENT_NAME" != "push" ]]; then
          echo "❌ This workflow should only run on push events"
          exit 1
        fi

        # Check if ref is a tag
        if [[ ! "$GITHUB_REF" =~ ^refs/tags/ ]]; then
          echo "❌ This workflow should only run for tags, got: $GITHUB_REF"
          exit 1
        fi

        # Extract tag name and check format
        TAG_NAME="${GITHUB_REF#refs/tags/}"
        if [[ ! "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "❌ Tag must be in format vX.Y.Z, got: $TAG_NAME"
          exit 1
        fi

        echo "✅ Valid tag event: $TAG_NAME"

    - name: Check if tag exists on current HEAD
      run: |
        TAG_NAME="${GITHUB_REF#refs/tags/}"

        # Get latest changes from main
        git pull origin main

        # Get the commit that the tag points to
        TAG_COMMIT=$(git rev-list -n 1 $TAG_NAME 2>/dev/null || echo "")

        if [ -z "$TAG_COMMIT" ]; then
          echo "❌ Tag $TAG_NAME not found"
          exit 1
        fi

        # Get current HEAD commit
        HEAD_COMMIT=$(git rev-parse HEAD)

        # Check if tag is on HEAD
        if [ "$TAG_COMMIT" != "$HEAD_COMMIT" ]; then
          echo "❌ Tag $TAG_NAME (commit: $TAG_COMMIT) is not on current HEAD (commit: $HEAD_COMMIT)"
          echo "Release tags must be created from the latest main branch"
          exit 1
        fi

        echo "✅ Tag $TAG_NAME is on current HEAD of main branch"

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Set up Python
      run: uv python install 3.11

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev

    - name: Install dependencies and run tests
      run: |
        uv sync --all-extras --dev
        echo "Running tests to ensure code quality..."
        uv run pytest --tb=short -q
        echo "✅ All tests passed!"

    - name: Extract version from tag
      id: extract_version
      run: |
        # Get tag name and remove 'v' prefix
        TAG_NAME="${GITHUB_REF#refs/tags/}"
        VERSION="${TAG_NAME#v}"
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Tag: $TAG_NAME, Version: $VERSION"

    - name: Update version in pyproject.toml, __init__.py and uv.lock
      run: |
        VERSION="${{ steps.extract_version.outputs.version }}"

        # Update pyproject.toml, __init__.py and uv.lock using Python for safety
        python << 'EOF'
        import re
        import os

        version = os.environ.get('VERSION', '${{ steps.extract_version.outputs.version }}')

        # Update pyproject.toml
        with open('pyproject.toml', 'r') as f:
            content = f.read()
        pattern = r'(version\s*=\s*["\'])([0-9]+\.[0-9]+\.[0-9]+(?:(?:a|b|rc|dev)[0-9]+)?)(["\'])'
        replacement = rf'\g<1>{version}\g<3>'
        content = re.sub(pattern, replacement, content)
        with open('pyproject.toml', 'w') as f:
            f.write(content)

        # Update src/palabra_ai/__init__.py
        with open('src/palabra_ai/__init__.py', 'r') as f:
            content = f.read()
        pattern = r'(__version__\s*=\s*["\'])([0-9]+\.[0-9]+\.[0-9]+(?:(?:a|b|rc|dev)[0-9]+)?)(["\'])'
        replacement = rf'\g<1>{version}\g<3>'
        content = re.sub(pattern, replacement, content)
        with open('src/palabra_ai/__init__.py', 'w') as f:
            f.write(content)

        # Update uv.lock if it exists
        if os.path.exists('uv.lock'):
            with open('uv.lock', 'r') as f:
                content = f.read()
            pattern = r'(\[\[package\]\]\s*\nname\s*=\s*"palabra-ai"\s*\nversion\s*=\s*")[^"]+(")'
            replacement = rf'\g<1>{version}\g<2>'
            content = re.sub(pattern, replacement, content, flags=re.MULTILINE)
            with open('uv.lock', 'w') as f:
                f.write(content)
        EOF

        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # Check if there are changes
        if git diff --quiet; then
          echo "No changes needed - version already matches tag"
          echo "skip_update=true" >> $GITHUB_ENV
        else
          # List changed files
          echo "Changed files:"
          git diff --name-only

          # Commit changes
          git add pyproject.toml src/palabra_ai/__init__.py

          # Add uv.lock if it was modified
          if [ -f "uv.lock" ] && git diff --name-only | grep -q "uv.lock"; then
            git add uv.lock
          fi

          git commit -m "🔖 Update version to $VERSION for release ${{ steps.extract_version.outputs.tag_name }}"
          echo "skip_update=false" >> $GITHUB_ENV
        fi

    - name: Push commit to main and update tag
      if: env.skip_update == 'false'
      run: |
        TAG_NAME="${{ steps.extract_version.outputs.tag_name }}"

        # Push the commit to main branch
        git push origin main

        # Delete the old tag locally and remotely
        git tag -d $TAG_NAME
        git push origin :refs/tags/$TAG_NAME

        # Create new tag at current HEAD
        git tag $TAG_NAME
        git push origin $TAG_NAME

        echo "✅ Version updated in main and tag $TAG_NAME moved to new commit"

    - name: Summary
      run: |
        if [ "${{ env.skip_update }}" == "true" ]; then
          echo "## No Update Needed 🟢" >> $GITHUB_STEP_SUMMARY
          echo "Version in pyproject.toml, __init__.py and uv.lock already matches tag ${{ steps.extract_version.outputs.tag_name }}" >> $GITHUB_STEP_SUMMARY
        else
          echo "## Version Updated! 🎉" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Tests**: ✅ All tests passed" >> $GITHUB_STEP_SUMMARY
          echo "- **Tag**: ${{ steps.extract_version.outputs.tag_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ steps.extract_version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Updated files**:" >> $GITHUB_STEP_SUMMARY
          echo "  - pyproject.toml" >> $GITHUB_STEP_SUMMARY
          echo "  - src/palabra_ai/__init__.py" >> $GITHUB_STEP_SUMMARY
          if [ -f "uv.lock" ]; then
            echo "  - uv.lock" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Commit pushed to main and tag moved to new commit." >> $GITHUB_STEP_SUMMARY
          echo "✅ Release workflow will be triggered automatically." >> $GITHUB_STEP_SUMMARY
        fi
